In [20]:
import math

In [21]:
import numpy as np

In [22]:
import array as arr

In [1]:
l=[1,2,"abc","xyz",8,9]
type(l)

list

In [7]:
np.array(((l)))

array(['1', '2', 'abc', 'xyz', '8', '9'], dtype='<U11')

In [8]:
type(np.array(l))

numpy.ndarray

In [10]:
np.array([[[1,4],[4,5],[8,9],["j","k"]]])

array([[['1', '4'],
        ['4', '5'],
        ['8', '9'],
        ['j', 'k']]], dtype='<U11')

In [11]:
np.array([1,2,3])

array([1, 2, 3])

In [12]:
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [13]:
type(np.array([1,2,3],ndmin=3))

numpy.ndarray

In [14]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
np.array([1,2,3],dtype=str)

array(['1', '2', '3'], dtype='<U1')

In [37]:
a=np.array([(1,2),(3,4)])

In [38]:
a

array([[1, 2],
       [3, 4]])

In [40]:
a[1][1]

4

In [41]:
l=[3,4,5,6,7]

In [42]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [43]:
np.array(l)

array([3, 4, 5, 6, 7])

In [44]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [45]:
arr=np.array([(1,2,5),(3,4,7),(6,7,8)])

In [47]:
arr

array([[1, 2, 5],
       [3, 4, 7],
       [6, 7, 8]])

In [48]:
arr[2][1]

7

In [49]:
arr[2][1]=87

In [50]:
arr

array([[ 1,  2,  5],
       [ 3,  4,  7],
       [ 6, 87,  8]])

In [51]:
arr[0:10]

array([[ 1,  2,  5],
       [ 3,  4,  7],
       [ 6, 87,  8]])

In [52]:
arr[-1]

array([ 6, 87,  8])

In [53]:
arr[0]

array([1, 2, 5])

In [54]:
for i in arr:
    print(i)

[1 2 5]
[3 4 7]
[ 6 87  8]


In [1]:
import numpy as np

In [2]:
import array as arr

In [3]:
import math

In [5]:
np.fromfunction(lambda i,j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [6]:
np.fromfunction(lambda i,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [7]:
np.fromfunction(lambda i,j :i/j,(3,3))

C:\Users\Rupali\AppData\Local\Temp\ipykernel_2468\3281559620.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j :i/j,(3,3))
C:\Users\Rupali\AppData\Local\Temp\ipykernel_2468\3281559620.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [8]:
np.fromstring("1,2,3,4",sep=",",dtype=int)

array([1, 2, 3, 4])

In [9]:
np.fromstring("1,2,3,4",sep=",",dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [10]:
np.fromstring("1,2,3,4",sep=",",dtype=float)

array([1., 2., 3., 4.])

In [11]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [12]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [13]:
np.arange(6,8,1)

array([6, 7])

In [14]:
np.arange(6,10,1)

array([6, 7, 8, 9])

In [15]:
np.arange(6,12,2)

array([ 6,  8, 10])

In [17]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [20]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

np.zeros(5)

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.zeros((2,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [29]:
np.ones((2,4,3))+5

array([[[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.empty(6)

array([1., 2., 3., 4., 5., 6.])

In [27]:
np.linspace(2,4,4,axis=0)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [31]:
np.logspace([2,3],4)

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [34]:
d=np.linspace(4,5,40)

In [35]:
d

array([4.        , 4.02564103, 4.05128205, 4.07692308, 4.1025641 ,
       4.12820513, 4.15384615, 4.17948718, 4.20512821, 4.23076923,
       4.25641026, 4.28205128, 4.30769231, 4.33333333, 4.35897436,
       4.38461538, 4.41025641, 4.43589744, 4.46153846, 4.48717949,
       4.51282051, 4.53846154, 4.56410256, 4.58974359, 4.61538462,
       4.64102564, 4.66666667, 4.69230769, 4.71794872, 4.74358974,
       4.76923077, 4.79487179, 4.82051282, 4.84615385, 4.87179487,
       4.8974359 , 4.92307692, 4.94871795, 4.97435897, 5.        ])

In [38]:
d.shape

(40,)

In [39]:
d.reshape(40,1)

array([[4.        ],
       [4.02564103],
       [4.05128205],
       [4.07692308],
       [4.1025641 ],
       [4.12820513],
       [4.15384615],
       [4.17948718],
       [4.20512821],
       [4.23076923],
       [4.25641026],
       [4.28205128],
       [4.30769231],
       [4.33333333],
       [4.35897436],
       [4.38461538],
       [4.41025641],
       [4.43589744],
       [4.46153846],
       [4.48717949],
       [4.51282051],
       [4.53846154],
       [4.56410256],
       [4.58974359],
       [4.61538462],
       [4.64102564],
       [4.66666667],
       [4.69230769],
       [4.71794872],
       [4.74358974],
       [4.76923077],
       [4.79487179],
       [4.82051282],
       [4.84615385],
       [4.87179487],
       [4.8974359 ],
       [4.92307692],
       [4.94871795],
       [4.97435897],
       [5.        ]])

In [40]:
d.reshape(20,2)

array([[4.        , 4.02564103],
       [4.05128205, 4.07692308],
       [4.1025641 , 4.12820513],
       [4.15384615, 4.17948718],
       [4.20512821, 4.23076923],
       [4.25641026, 4.28205128],
       [4.30769231, 4.33333333],
       [4.35897436, 4.38461538],
       [4.41025641, 4.43589744],
       [4.46153846, 4.48717949],
       [4.51282051, 4.53846154],
       [4.56410256, 4.58974359],
       [4.61538462, 4.64102564],
       [4.66666667, 4.69230769],
       [4.71794872, 4.74358974],
       [4.76923077, 4.79487179],
       [4.82051282, 4.84615385],
       [4.87179487, 4.8974359 ],
       [4.92307692, 4.94871795],
       [4.97435897, 5.        ]])

In [43]:
d.reshape(2,1,20)

array([[[4.        , 4.02564103, 4.05128205, 4.07692308, 4.1025641 ,
         4.12820513, 4.15384615, 4.17948718, 4.20512821, 4.23076923,
         4.25641026, 4.28205128, 4.30769231, 4.33333333, 4.35897436,
         4.38461538, 4.41025641, 4.43589744, 4.46153846, 4.48717949]],

       [[4.51282051, 4.53846154, 4.56410256, 4.58974359, 4.61538462,
         4.64102564, 4.66666667, 4.69230769, 4.71794872, 4.74358974,
         4.76923077, 4.79487179, 4.82051282, 4.84615385, 4.87179487,
         4.8974359 , 4.92307692, 4.94871795, 4.97435897, 5.        ]]])

In [44]:
np.random.rand(3)

array([0.49561996, 0.70457687, 0.15264733])

In [45]:
np.random.rand(5,4)

array([[0.90089512, 0.98648484, 0.19819266, 0.40702282],
       [0.47687837, 0.27137055, 0.4690501 , 0.08778327],
       [0.60371208, 0.56989153, 0.56054629, 0.22375387],
       [0.44862808, 0.07921152, 0.21821993, 0.0949636 ],
       [0.42092153, 0.09960101, 0.89767965, 0.69792321]])

In [46]:
np.random.rand(5,5)

array([[0.27000505, 0.05594589, 0.60850574, 0.04339828, 0.46636821],
       [0.48903224, 0.5951478 , 0.23658729, 0.39550763, 0.08993681],
       [0.74947372, 0.62319441, 0.81507786, 0.05906991, 0.80946351],
       [0.91336479, 0.95725117, 0.3015309 , 0.34936833, 0.20584569],
       [0.29522664, 0.52807856, 0.17109853, 0.26659156, 0.07542187]])

In [47]:
np.random.rand(2,2,3)

array([[[0.00107786, 0.71587857, 0.10695401],
        [0.99562288, 0.64103549, 0.5955636 ]],

       [[0.77325377, 0.47116049, 0.74966501],
        [0.92208112, 0.29800719, 0.18897144]]])

In [48]:
np.random.randint(6)

3

In [49]:
np.random.randint((5,6),40)

array([29, 22])

In [50]:
np.random.randint(5,6,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [51]:
np.random.randn(4,4)

array([[-1.51697844, -0.64253176, -0.56030898,  0.19422952],
       [ 0.64137026, -1.58149955,  0.15943622,  0.70467089],
       [-1.25481682,  0.79781331, -1.45891094,  0.68309744],
       [-0.30558343, -0.9296473 , -1.29167097, -1.07066177]])

In [52]:
arr=np.random.randint(3,9,(3,3))

In [53]:
arr

array([[5, 5, 7],
       [3, 4, 7],
       [8, 7, 8]])

In [55]:
arr.reshape(1,1,9)

array([[[5, 5, 7, 3, 4, 7, 8, 7, 8]]])

In [56]:
arr.reshape(3,3,1)

array([[[5],
        [5],
        [7]],

       [[3],
        [4],
        [7]],

       [[8],
        [7],
        [8]]])

In [57]:
arr.reshape(3,-1)

array([[5, 5, 7],
       [3, 4, 7],
       [8, 7, 8]])

In [58]:
arr.reshape(3,-4556)

array([[5, 5, 7],
       [3, 4, 7],
       [8, 7, 8]])

In [60]:
arr.max()

8

In [61]:
arr.min()

3

In [62]:
arr=np.random.randint(4,100,(5,5))

In [64]:
arr

array([[47, 99, 77, 68, 57],
       [ 4, 53, 69, 57, 83],
       [65, 90, 34, 13,  5],
       [69, 48, 91, 39, 65],
       [40, 39, 10, 32, 90]])

In [65]:
arr[3:,3:]

array([[39, 65],
       [32, 90]])

In [66]:
arr[2:,2:]

array([[34, 13,  5],
       [91, 39, 65],
       [10, 32, 90]])

In [67]:
arr[:,[1,3]]

array([[99, 68],
       [53, 57],
       [90, 13],
       [48, 39],
       [39, 32]])

In [70]:
arr

array([[47, 99, 77, 68, 57],
       [ 4, 53, 69, 57, 83],
       [65, 90, 34, 13,  5],
       [69, 48, 91, 39, 65],
       [40, 39, 10, 32, 90]])

In [68]:
arr>10

array([[ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True]])

In [69]:
arr[arr>10]

array([47, 99, 77, 68, 57, 53, 69, 57, 83, 65, 90, 34, 13, 69, 48, 91, 39,
       65, 40, 39, 32, 90])

In [71]:
arr*arr

array([[2209, 9801, 5929, 4624, 3249],
       [  16, 2809, 4761, 3249, 6889],
       [4225, 8100, 1156,  169,   25],
       [4761, 2304, 8281, 1521, 4225],
       [1600, 1521,  100, 1024, 8100]])

In [72]:
arr1=np.random.randint(2,5,(2,2))

In [73]:
arr1

array([[4, 2],
       [4, 2]])

In [74]:
arr2=np.random.randint(2,5,(2,2))

In [75]:
arr2

array([[2, 4],
       [3, 3]])

In [76]:
arr1*arr2

array([[ 8,  8],
       [12,  6]])

In [77]:
arr1@arr2

array([[14, 22],
       [14, 22]])

In [78]:
arr**2

array([[2209, 9801, 5929, 4624, 3249],
       [  16, 2809, 4761, 3249, 6889],
       [4225, 8100, 1156,  169,   25],
       [4761, 2304, 8281, 1521, 4225],
       [1600, 1521,  100, 1024, 8100]], dtype=int32)

In [79]:
arr/0

C:\Users\Rupali\AppData\Local\Temp\ipykernel_2468\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [80]:
np.log(arr1) #log value

array([[1.38629436, 0.69314718],
       [1.38629436, 0.69314718]])

In [83]:
np.random.seed(13)
np.random.rand(3,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651],
       [0.64161334, 0.72201823, 0.03503652, 0.29844947]])

In [89]:
np.random.seed(2)
np.random.rand(3,5)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987]])